# Generated by Django 4.1 on 2022-09-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_catagories_templetes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='Page_pic',
            field=models.ImageField(blank=True, default='page.png', null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='templetes',
            name='Template_pic',
            field=models.ImageField(blank=True, default='template.png', null=True, upload_to='profiles/'),
        ),
    ]
